/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Posto;

/**
 *
 * @author Usuário
 */
public class RelatorioAgendamentosView extends javax.swing.JFrame {

    private TableModelAgendamento tableModelAgendamento;

    /**
     * Creates new form RelatorioAgendamentosView
     */
    public RelatorioAgendamentosView() {
        this.tableModelAgendamento = new TableModelAgendamento(Posto.getPosto().getAgendamentos());
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taAgendamentos = new javax.swing.JTable();
        btVacinar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agendamentos");

        taAgendamentos.setModel(this.tableModelAgendamento);
        jScrollPane1.setViewportView(taAgendamentos);

        btVacinar.setText("Vacinar");
        btVacinar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVacinarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVacinar)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVacinar)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVacinarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVacinarActionPerformed

        //-1 é quando a linha não está selecionada.
        if (taAgendamentos.getSelectedRow() != -1) {
            tableModelAgendamento.removeRow(taAgendamentos.getSelectedRow());
        }

    }//GEN-LAST:event_btVacinarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btVacinar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable taAgendamentos;
    // End of variables declaration//GEN-END:variables
}
