/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Agendamento;
import Model.Endereco;
import Model.Fabricante;
import Model.Medico;
import Model.Paciente;
import Model.Posto;
import Model.Vacina;
import java.util.ArrayList;

/**
 *
 * @author Usuário
 */
public class SistemaPostoView extends javax.swing.JFrame {

    private ArrayList<Fabricante> fabricantes;

    /**
     * Creates new form SistemaPostoView
     */
    public SistemaPostoView() {
        this.fabricantes = new ArrayList<>();
        initComponents();
    }

    public ArrayList<Fabricante> getFabricantes() {
        return fabricantes;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mbSistemaPosto = new javax.swing.JMenuBar();
        mnRelatorios = new javax.swing.JMenu();
        miRelatorioAgendamentos = new javax.swing.JMenuItem();
        miRelatorioEstoque = new javax.swing.JMenuItem();
        miRelatorioPacientes = new javax.swing.JMenuItem();
        miRelatorioMedicos = new javax.swing.JMenuItem();
        mnEstoque = new javax.swing.JMenu();
        miAdicionar = new javax.swing.JMenuItem();
        miRemover = new javax.swing.JMenuItem();
        mnCadastros = new javax.swing.JMenu();
        miCadastroAgendamento = new javax.swing.JMenuItem();
        miCadastroPaciente = new javax.swing.JMenuItem();
        miCadastroMedico = new javax.swing.JMenuItem();
        miCadastroFabricante = new javax.swing.JMenuItem();
        miCadastroVacina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VacinaE");

        mnRelatorios.setText("Relatórios");

        miRelatorioAgendamentos.setText("Agendamentos");
        miRelatorioAgendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioAgendamentosActionPerformed(evt);
            }
        });
        mnRelatorios.add(miRelatorioAgendamentos);

        miRelatorioEstoque.setText("Estoque");
        miRelatorioEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioEstoqueActionPerformed(evt);
            }
        });
        mnRelatorios.add(miRelatorioEstoque);

        miRelatorioPacientes.setText("Pacientes");
        miRelatorioPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioPacientesActionPerformed(evt);
            }
        });
        mnRelatorios.add(miRelatorioPacientes);

        miRelatorioMedicos.setText("Medicos");
        miRelatorioMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRelatorioMedicosActionPerformed(evt);
            }
        });
        mnRelatorios.add(miRelatorioMedicos);

        mbSistemaPosto.add(mnRelatorios);

        mnEstoque.setText("Estoque");

        miAdicionar.setText("Adicionar");
        miAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAdicionarActionPerformed(evt);
            }
        });
        mnEstoque.add(miAdicionar);

        miRemover.setText("Remover");
        miRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemoverActionPerformed(evt);
            }
        });
        mnEstoque.add(miRemover);

        mbSistemaPosto.add(mnEstoque);

        mnCadastros.setText("Cadastros");

        miCadastroAgendamento.setText("Agendamento");
        miCadastroAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroAgendamentoActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadastroAgendamento);

        miCadastroPaciente.setText("Paciente");
        miCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPacienteActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadastroPaciente);

        miCadastroMedico.setText("Médico");
        miCadastroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroMedicoActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadastroMedico);

        miCadastroFabricante.setText("Fabricante");
        miCadastroFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroFabricanteActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadastroFabricante);

        miCadastroVacina.setText("Vacina");
        miCadastroVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroVacinaActionPerformed(evt);
            }
        });
        mnCadastros.add(miCadastroVacina);

        mbSistemaPosto.add(mnCadastros);

        setJMenuBar(mbSistemaPosto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miRelatorioMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioMedicosActionPerformed
        RelatorioMedicosView relMedicosView = new RelatorioMedicosView();
        relMedicosView.setVisible(true);
    }//GEN-LAST:event_miRelatorioMedicosActionPerformed

    private void miCadastroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroMedicoActionPerformed
        CadastroMedicoView cadMedicoView = new CadastroMedicoView(this);
        cadMedicoView.setVisible(true);
    }//GEN-LAST:event_miCadastroMedicoActionPerformed

    private void miCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPacienteActionPerformed
        CadastroPacienteView cadPacienteView = new CadastroPacienteView(this);
        cadPacienteView.setVisible(true);
    }//GEN-LAST:event_miCadastroPacienteActionPerformed

    private void miRelatorioPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioPacientesActionPerformed
        RelatorioPacientesView relPacientesView = new RelatorioPacientesView();
        relPacientesView.setVisible(true);
    }//GEN-LAST:event_miRelatorioPacientesActionPerformed

    private void miCadastroAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroAgendamentoActionPerformed
        CadastroAgendamentoView cadAgendamentoView = new CadastroAgendamentoView(this);
        cadAgendamentoView.setVisible(true);
    }//GEN-LAST:event_miCadastroAgendamentoActionPerformed

    private void miRelatorioAgendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioAgendamentosActionPerformed
        RelatorioAgendamentosView relAgendamentosView = new RelatorioAgendamentosView();
        relAgendamentosView.setVisible(true);
    }//GEN-LAST:event_miRelatorioAgendamentosActionPerformed

    private void miCadastroVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroVacinaActionPerformed
        CadastroVacinaView cadVacinaView = new CadastroVacinaView(this);
        cadVacinaView.setVisible(true);
    }//GEN-LAST:event_miCadastroVacinaActionPerformed

    private void miCadastroFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroFabricanteActionPerformed
        CadastroFabricanteView cadFabricanteView = new CadastroFabricanteView(this);
        cadFabricanteView.setVisible(true);
    }//GEN-LAST:event_miCadastroFabricanteActionPerformed

    private void miRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRelatorioEstoqueActionPerformed
        RelatorioEstoqueView relEstoqueView = new RelatorioEstoqueView();
        relEstoqueView.setVisible(true);
    }//GEN-LAST:event_miRelatorioEstoqueActionPerformed

    private void miAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAdicionarActionPerformed
        AdicionaVacinaView addVacinaView = new AdicionaVacinaView();
        addVacinaView.setVisible(true);
    }//GEN-LAST:event_miAdicionarActionPerformed

    private void miRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemoverActionPerformed
        DescontaVacinaView descVacinaView = new DescontaVacinaView();
        descVacinaView.setVisible(true);
    }//GEN-LAST:event_miRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaPostoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaPostoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaPostoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaPostoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaPostoView().setVisible(true);
            }
        });

        Posto posto = Posto.getPosto();
        
        //Endereços
        Endereco e1 = new Endereco("Rua 1 de Maio", "Centro", "Dona Emma", 28);
        Endereco e2 = new Endereco("Rua Adolfo Weidmann", "Nova Esperança", "Dona Emma", 157);
        Endereco e3 = new Endereco("Rua Alexandre Lenard", "Nova Esperança", "Dona Emma", 334);
        Endereco e4 = new Endereco("Rua Dona Helena", "Nova Esperança", "Dona Emma", 54);
        
        //Pacientes
        Paciente p1 = new Paciente("Diabetes", "João Matias", 38, 264365681, 998756445, e1);
        Paciente p2 = new Paciente("Nenhuma", "José Severino", 75, 552578741, 997564893, e2);
        Paciente p3 = new Paciente("Hipertensão", "Maria Voigt", 54, 162983476, 996102678, e3);
        Paciente p4 = new Paciente("Arritimia", "Fernanda Ferreira", 33, 762688311, 998649035, e4);
        Paciente p5 = new Paciente("Nenhuma", "Antonio Guesser", 46, 572699201, 996427113, e2);
        Paciente p6 = new Paciente("Nenhuma", "Mauricio de Souza", 75, 897254098, 988904826, e3);
        
        posto.addPaciente(p1);
        posto.addPaciente(p2);
        posto.addPaciente(p3);
        posto.addPaciente(p4);
        posto.addPaciente(p5);
        posto.addPaciente(p6);
        
        //Médicos
        Medico m1 = new Medico("Infectologia", "Jucélia Ferreira", 33, 757689712, 998649035, e4);
        Medico m2 = new Medico("Clinico Geral", "Helena Silva", 45, 724688311, 998765892, e2);
        
        posto.addMedico(m1);
        posto.addMedico(m2);
        
        //Agendamento
        Agendamento a1 = new Agendamento("26/08/2021", p1.getNome(), p1.getCpf());
        Agendamento a2 = new Agendamento("27/11/2021", p1.getNome(), p1.getCpf());
        Agendamento a3 = new Agendamento("12/09/2021", p2.getNome(), p2.getCpf());
        Agendamento a4 = new Agendamento("14/12/2021", p2.getNome(), p2.getCpf());
        Agendamento a5 = new Agendamento("30/10/2021", p3.getNome(), p3.getCpf());
        Agendamento a6 = new Agendamento("25/10/2021", p4.getNome(), p4.getCpf());
        Agendamento a7 = new Agendamento("18/12/2021", p5.getNome(), p5.getCpf());
        Agendamento a8 = new Agendamento("09/09/2021", p6.getNome(), p6.getCpf());
        
        posto.addAgendamento(a1);
        posto.addAgendamento(a2);
        posto.addAgendamento(a3);
        posto.addAgendamento(a4);
        posto.addAgendamento(a5);
        posto.addAgendamento(a6);
        posto.addAgendamento(a7);
        posto.addAgendamento(a8);
        
        //Vacinas e fabricantes
        Fabricante f1 = new Fabricante("Fiocruz");
        Fabricante f2 = new Fabricante("Pfizer");
        Fabricante f3 = new Fabricante("União Química");    
        
        Vacina v1 = new Vacina("AstraZaneca", 5.0, 18, f1);
        Vacina v2 = new Vacina("Cominarty", 4.5, 25, f2);
        Vacina v3 = new Vacina("Sputnik V", 3.5, 12, f3);
        
        posto.getEstoque().addVacina(v1);
        posto.getEstoque().addVacina(v2);
        posto.getEstoque().addVacina(v3);
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mbSistemaPosto;
    private javax.swing.JMenuItem miAdicionar;
    private javax.swing.JMenuItem miCadastroAgendamento;
    private javax.swing.JMenuItem miCadastroFabricante;
    private javax.swing.JMenuItem miCadastroMedico;
    private javax.swing.JMenuItem miCadastroPaciente;
    private javax.swing.JMenuItem miCadastroVacina;
    private javax.swing.JMenuItem miRelatorioAgendamentos;
    private javax.swing.JMenuItem miRelatorioEstoque;
    private javax.swing.JMenuItem miRelatorioMedicos;
    private javax.swing.JMenuItem miRelatorioPacientes;
    private javax.swing.JMenuItem miRemover;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenu mnEstoque;
    private javax.swing.JMenu mnRelatorios;
    // End of variables declaration//GEN-END:variables
}
